const SCREEN_NAMES = {
    INITIAL_LOGIN_SCREEN: "InitialLoginScreen",
    LOGIN_SCREEN: "LoginScreen",
    SSO_LOGIN_SCREEN: "SSOLoginScreen",
    DRAWER_SCREENS: "DrawerScreenCalendar",
    CALENDAR_SCREEN: "Calendar",
    ASSESSMENT_SCREEN: "Grading & Assessment",
    TRAINEE_REVIEW: "Trainee Review",
    PENDING_GRADING: "Pending Grading",
    CAT:"CAT II/III Line Events",
    GRADING: "Grading",
    SLF_GRADING: "Sector Information",
    GRADING_HISTORY: "Grading History",
    SLF_HISTORY: "SLF HISTORY",
    SKILL_TEST_FORM: "SkillTestForm",
    FORM_GRADING_TAB: "Grading",
    FORM_OVERALL_OUTCOME: "Overall Outcome",
    SLF_FORM_OVERALL_OUTCOME: "Grading",
    LVTO_TRAINING: "Training",
    LVTO_CHECK: "Check",
    TRAINING: "Training",
    CHECK: "Check",
    FORM_GRADING_COMPLETE: "Grading Complete",
    FORM_HISTORY: "History",
    GRADING_TAB_HOME: "Home",
    STACK_SCREEN: "StackScreens",
    TESTING_SCREEN: "TestingDrawerScreen",
    FORMS_TAB_SCREEN: "FormsTabScreens",
    TRAINING: "Training",
    CHECK: "Check",
  };
  
  export default SCREEN_NAMES;
  